# Site settings
title: Adrian Russell
copyright: "Copyright © 2018 - Adrian Russell"
description: "Adrian Russell is a software engineer based in the South West of England, UK. Adrian specialises in development for iOS and Mac OS X."
baseurl: ""
url: "https://adrianrussell.co.uk"
twitter_username:  ade177
github_username:   aderussell
linkedin_url: https://uk.linkedin.com/in/adrian-russell-4b15aa74

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title


sass:
    sass_dir: stylesheets
    style: compressed

gems:
    - jekyll-sitemap
    - jekyll-redirect-from