# Site settings
title: Adrian Russell
copyright: "Copyright. 2014. Adrian Russell"
# email: your-email@domain.com
description: "A software engineer based in Plymouth, UK. Specialises in development for iOS and Mac OS X."
baseurl: ""
url: "http://adrianrussell.co.uk"
twitter_username:  ade177
github_username:   aderussell
linkedin_username: 264236101

# Build settings
markdown: kramdown
permalink: /blog/:title

gems:
- jekyll-sitemap